name: Time Series Metrics

on:
  workflow_dispatch:

jobs:
  python-build-n-publish:
    name: Build and publish Python distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2  # Corrigido para v2

      - name: Initialize Python 3.9
        uses: actions/setup-python@v2  # Corrigido para v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Install dependencies with poetry
        run: poetry install  # Corrigido o nome do passo

      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@v2  # Recomendado usar uma versão estável
        with:
          password: ${{ secrets.test_pypi_password }}
          repository_url: https://pypi.org/project/timeseriesmetrics/
